### ISSUE TITLE
Good project. Will jsxt2 support Chakra engine?

### ISSUE THREAD

**Issue by HuangShumin** [ildar-shaimordanov/jsxt2#1]
.

**Comment by ildar-shaimordanov** [comment]
Chakra has its own CLI at https://github.com/microsoft/ChakraCore
NodeJS supports Chakra at https://github.com/nodejs/node-chakracore

I don't set goals to cover everything. It's just attempt to close existing lack. As soon as Chakra becomes shipped with Windows itself, this project will be stopped or transformed to follow reality.
