### ISSUE TITLE
Will jsxt2 support Ctrl-V to paste code snippets to REPL?

### ISSUE THREAD

**Issue by HuangShumin** [ildar-shaimordanov/jsxt2#2]
thanks.

**Comment by ildar-shaimordanov** [comment]
Yes. It already supports. Just follow this procedure:
type `::`, then press `<ENTER>` to start the multiline mode
paste a snippet with `CTRL-V>`, then press `<ENTER>`
type `::` and press `<ENTER>` to stop the multiline mode
